version: '3'

networks:
  default:
    external:
      name: food_network

services:
  fdr-backend:
    build: .
    command: 'npm run dev'
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - NODE_ENV=development
    volumes:
      - food-done-right-sync:/food-done-right:nocopy
    container_name: food-done-right

volumes:
  food-done-right-sync:
    external: true
