version: '3'

networks:
  default:
    external:
      name: food_network

services:
  fdr-backend:
    build: .
    command: 'npm run start'
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
